apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-08T15:59:08Z"
  generation: 1
  labels:
    app: security-codes-web
  name: security-codes-web
  namespace: default
  resourceVersion: "51562"
  selfLink: /apis/apps/v1/namespaces/default/deployments/security-codes-web
  uid: a4cab6f5-947f-4f36-89e5-213f17125ff3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: security-codes-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: security-codes-web
    spec:
      containers:
      - image: caprilespe/security-codes-web:v1
        imagePullPolicy: IfNotPresent
        name: security-codes-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-08T15:59:19Z"
    lastUpdateTime: "2021-12-08T15:59:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-08T15:59:08Z"
    lastUpdateTime: "2021-12-08T15:59:19Z"
    message: ReplicaSet "security-codes-web-578f6b566" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
