apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-08T16:07:21Z"
  labels:
    app: security-codes-web
  name: security-codes-web
  namespace: default
  resourceVersion: "51686"
  selfLink: /api/v1/namespaces/default/services/security-codes-web
  uid: 2624cbea-182e-4b06-ab95-a18ce26060c1
spec:
  clusterIP: 10.99.90.117
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30788
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: security-codes-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
